from tqdm.auto import tqdm
import pandas as pd
from openai import OpenAI
from textwrap import dedent
from judges.base import BaseJudge, Judgment
from judges.graders.correctness import PrometheusAbsoluteCoarseCorrectness


# Set the model use change this as need to call different model
# when run the script will look for the API key and secret key at local environment
# If you are using ollama locally setting this is unneeded.
JUDGE_MODEL = "ollama/gpt-oss:20b"

# 
class KnowledgeGraphJudge(BaseJudge):
    def judge(
            self,
            input: str,
            output: str = None,
            expected: str = None,
    ) -> Judgment:
        """    
        Parameters:
        -----------
        input: str
            The input provided to the model to be judged.
        output: str  
            The output generated by the model.
        expected: str
            The expected output for comparison (optional).
        
        Returns:
        --------
        Judgment:
            The evaluation result containing the score and reasoning.
        """
        system_prompt = "You are a financial domain expert"
        user_prompt = dedent(
            f"""
            Evaluate whether the following response is correct base on the provided information

            Original questions: {input}
            Response to evaluate: {output}

            Return a score from 1 to 5 with 1 being the least and 5 being the best
            """
        )
        
        reasoning, score = self._judge(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
        )

        return Judgment(reasoning=reasoning,score=score, score_type="numerical")

def judging_output(
            questions_path: str,
            model_output_path: str,
            model: BaseJudge,
            metric_name: str,
            save_output: bool = True,
            file_name: str = "llm_evaluation.csv",
            num_samples: int = 1
) -> None:
    questions_df = pd.read_csv(questions_path)
    model_output_df = pd.read_csv(model_output_path)
    combined_df = pd.concat([questions_df, model_output_df], axis=1)
    print(f"Number of questions {combined_df.shape}")
    result_df = pd.DataFrame(columns=[metric_name])
    scores = []
    reasons = []

    for idx, row in tqdm(combined_df.iterrows(), total=combined_df.shape[0], desc="Evaluating Output..."):
        try:
            question = row["questions"],
            output = row["output"],
            expected = row["expected"]
            judgment = model.judge(
                input=question,
                output=output,
                expected=expected,
            )
            score_val = judgment.score if isinstance(judgment.score, (int, float)) else 0
            reason_val = getattr(judgment, "reasoning", "")
        except Exception as e:
            score_val = 0
            reason_val = f"judge error: {e}"
        if idx < 2:
            print(f"[DEBUG] idx={idx}, question={question} score={score_val} reason={reason_val}")
        scores.append(score_val)
        reasons.append(reason_val)

    result_df = pd.DataFrame({metric_name: scores, "reasoning": reasons})
    if save_output:
        result_df.to_csv(file_name, index=False)
    print("Evaluation completed")
    return result_df
    return None

if __name__ == "__main__":
    # Demo how to use
    TEST_QUESTION = "dummy_questions_llm_judge.csv"
    TEST_OUTPUT = "dummy_answers_llm_judge.csv"
    correctness_judge = PrometheusAbsoluteCoarseCorrectness(model=JUDGE_MODEL)
    judging_output(
        questions_path=TEST_QUESTION,
        model_output_path=TEST_OUTPUT,
        model=correctness_judge,
        metric_name="correctness",
    )
