# generated by datamodel-codegen:
#   filename:  financial_schema.json
#   timestamp: 2026-01-11T10:36:55+00:00

from __future__ import annotations

from pydantic import BaseModel


class Entity(BaseModel):
    name: str
    entity_type: str


class Relationship(BaseModel):
    relationship: str
    evidence: str


class Target(BaseModel):
    name: str
    entity_type: str


class TemporalInfo(BaseModel):
    date: str
    extraction_type: str


class Model(BaseModel):
    triplet_id: str
    entity: Entity
    relationship: Relationship
    target: Target
    temporal_info: TemporalInfo
    ticker: str
    source_url: str
    source_text: str
    chunk_text: str
    chunk_id: str
    page_id: str
